version: '2'
services:
  database:
    image: postgres
    restart: always

  rabbitmq:
    image: rabbitmq
    restart: always
    volumes:
      - ./data/rabbitmq/:/var/lib/rabbitmq

  murmur:
    image: tf2stadium/murmur
    restart: always
    env_file: env/murmur.env