version: '2'
services:
  database:
    image: postgres
    restart: always

  rabbitmq:
    image: rabbitmq
    restart: always

  murmur:
    image: tf2stadium/murmur
    restart: always
    env_file: env/murmur.env