version: '2'
services:
  helen:
    image: tf2stadium/helen:dev
    restart: on-failure
    depends_on:
      - database
      - rabbitmq
      - pauling
      - fumble
    env_file: env/helen-dev.env

    ports:
      - "8080:80"
      - "8081:81"
      #DISABLE FUMBLE FOR DEV
    entrypoint: /bin/helen -disable_pauling=false -disable_fumble=false
    stop_signal: SIGTERM

  frontend:
    image: tf2stadium/frontend:dev
    depends_on:
      - helen
    environment:
      - WS_ENDPOINT=
      - API_ENDPOINT=
    ports:
      - "80:80"

  database:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=dickbutt
    - POSTGRES_USER=tf2stadium
    - POSTGRES_DB=tf2stadium
    volumes:
    - /var/lib/postgresql
    - /etc/postgresql
    - /var/log/postgresql

  rabbitmq:
    image: rabbitmq

  murmur:
    image: vibhavp/murmur
    environment:
      #CHANGE THIS
      - MURMUR_PASSWORD=
    ports:
      - "64738:64738/tcp"
      - "64378:64738/udp"

  fumble:
    image: tf2stadium/fumble
    restart: on-failure
    depends_on:
      - database
      - murmur
      - rabbitmq
    env_file: env/fumble-prod.env
    ports:
      - "8082:80"

  pauling:
    image: tf2stadium/pauling:dev
    restart: on-failure
    stop_signal: SIGTERM
    depends_on:
      - database
      - rabbitmq
    ports:
      - "8002:8002/udp"
    environment:
    - PAULING_RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    - PAULING_DATABASE_ADDR=database:5432
